# Package Overview
package_name: cls_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (survival)
target: survived

pipeline_name: classification_model
pipeline_save_file: classification_model_output_v


features:
  - sex
  - cabin
  - embarked
  - title
  - age
  - fare
# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

alpha: 0.001

# categorical variables with NA in train set
categorical_vars_with_na_frequent:
  - BsmtQual
  - BsmtExposure
  - BsmtFinType1
  - GarageFinish

categorical_vars_with_na_missing:
  - FireplaceQu

numerical_vars_with_na:
  - LotFrontage

temporal_vars:
  - YearRemodAdd


# variables to log transform
numericals_log_vars:
  - LotFrontage
  - FirstFlrSF
  - GrLivArea

binarize_vars:
  - ScreenPorch

# variables to map
qual_vars:
  - ExterQual
  - BsmtQual
  - HeatingQC
  - KitchenQual
  - FireplaceQu

exposure_vars:
  - BsmtExposure

finish_vars:
  - BsmtFinType1

garage_vars:
  - GarageFinish

categorical_vars:
  - sex
  - cabin
  - embarked
  - title

exposure_mappings:
  No: 1
  Mn: 2
  Av: 3
  Gd: 4


finish_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  LwQ: 2
  Rec: 3
  BLQ: 4
  ALQ: 5
  GLQ: 6


garage_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  RFn: 2
  Fin: 3